### ISSUE TITLE
Some question about evaluation_threedmatch.py

### ISSUE THREAD

**Issue by Yellowshuohahaha** [felja633/RLLReg#1]
I download RGB-D scenes from 3dmatch and pre-trained models. After set pretrained_networks and 3dmatch dataset to the path of that folder in config.py, I run the following script:
python evaluation_threedmatch.py 
=> loading checkpoint '/home/s206/disk/pycharmproject/RLLReg-master/data/models/ResUNetBN2C-feat32-3dmatch-v0.05.pth'
=> Setting voxel size to 0.05
=> loading finished
generate samples...
evaluate batch 0 ...
RLLReg
resample time: 449.2 ms
extract time: 644.6 ms
Traceback (most recent call last):
  File "evaluation_threedmatch.py", line 140, in <module>
    max_err_R=4.0, max_err_t=0.3, success_R=4, success_t=0.1, save_errors=True, plot=False)
  File "/home/s206/disk/pycharmproject/RLLReg-master/evaluation/evaluate.py", line 36, in benchmark
    errors[m.params.name].append(evaluate_registration(m, batch, vis, save=save))
  File "/home/s206/disk/pycharmproject/RLLReg-master/evaluation/evaluate.py", line 10, in evaluate_registration
    out = method(data)
  File "/home/s206/anaconda3/envs/rllreg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/s206/disk/pycharmproject/RLLReg-master/models/rll_model_fcgf.py", line 164, in forward
    assert f.shape[0] == inds_list[ind_cnt].shape[0]
AssertionError
 It seems the code doesn't run rightly. My torch version is 1.7 and minkowskiEngine version is 0.4. Can you help me?

**Comment by felja633** [comment]
I see, it is probably some changes in Minkowski engine that makes my indexing to break. I will try to make this part more robust when I have the time. Thank you for pointing it out

**Comment by Yellowshuohahaha** [comment]
> I see, it is probably some changes in Minkowski engine that makes my indexing to break. I will try to make this part more robust when I have the time. Thank you for pointing it out

Thank you very much! Looking forword to your work.

**Comment by Yellowshuohahaha** [comment]
Hi @felja633 , may I ask if reducing the Minkowski engine version can solve this problem? I want to use this project to do some engineering point cloud registration applications. Thanks.

**Comment by felja633** [comment]
That could solve the problem. Try checking out a version from last year, at least that has worked for me in the passed
